version: '3.8'

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env  # Indica que las variables de entorno provienen del archivo .env
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge